name: Lint

on:
  pull_request:
    branches: [master]

jobs:
  eslint:
    runs-on: ubuntu-latest
    container:
      image: node:16.18.0-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Cache node.js modules
        uses: actions/cache@v3
        env:
          cache-name: npm-${{ hashFiles('package-lock.json') }}
        with:
          path: |
           .npm
          key: ${{ env.cache-name }}
          restore-keys: |
           ${{ env.cache-name }}
      - name: Install dependencies
        run: npm ci
      - name: Lint source code with ESLint
        run: npx eslint .eslintrc.js src/ --ext .js,.jsx,.ts,.tsx,.json

  prettier:
    runs-on: ubuntu-latest
    container:
      image: node:16.18.0-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Cache node.js modules
        uses: actions/cache@v3
        env:
          cache-name: npm-${{ hashFiles('package-lock.json') }}
        with:
          path: |
           .npm
          key: ${{ env.cache-name }}
          restore-keys: |
           ${{ env.cache-name }}
      - name: Install dependencies
        run: npm ci
      - name: Lint source code with Prettier
        run: npx prettier --check src/ --ext .js,.jsx,.ts,.tsx,.json

