name: Lint

on:
  pull_request:
    branches: [master]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node.js modules
        id: cache-step
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install dependencies
        if: steps.cache-step.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lint source code with ESLint
        run: ./node_modules/.bin/eslint .eslintrc.js src/ --ext .js,.jsx,.ts,.tsx,.json

  prettier:
    runs-on: ubuntu-latest
    container:
      image: node:16.18.0-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint source code with Prettier
        run: npx prettier --check src/ --ext .js,.jsx,.ts,.tsx,.json

