name: Lint

on:
  pull_request:
    branches: [master]

jobs:
  eslint:
    runs-on: ubuntu-latest
    container:
      image: node:16.18.0-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Cache node.js modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build.${{ env.cache-name }}-
            ${{ runner.os }}-build
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Lint source code with ESLint
        run: npx eslint .eslintrc.js src/ --ext .js,.jsx,.ts,.tsx,.json

  prettier:
    runs-on: ubuntu-latest
    container:
      image: node:16.18.0-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint source code with Prettier
        run: npx prettier --check src/ --ext .js,.jsx,.ts,.tsx,.json

